---
baseurl: http://supportstaging.balsamiq.com
config: config.yaml
languagecode: en-us
metadataformat: yaml
paginate: '50'
pluralizelisttitles: ''
theme: support-balsamiq-com
title: Balsamiq Support Portal
pagesize: '50'
blackfriday:
  plainIdAnchors: true
taxonomies:
  category: categories
  tag: tags
params:
  balsamiqcomurl: https://balsamiq.com
pygmentsuseclasses: true
pygmentsstyle: monokai
---
